# Site settings
title: RAZA
email: alina.soare37@gmail.com
author: alina
description:

baseurl:"raza"

# Build settings
permalink: /:categories/:year/:month/:day/:title:output_ext

sass:
  sass_dir: css

  # Social icons
show_social_icons: true
github_username: alina-soare
facebook_username: alina.soare.1420

# plugins
plugins: [jekyll-paginate]
paginate: 3