# Site settings
title: RAZA
email: "alina.soare37@gmail.com"
author: alina
baseurl: "/raza"



sass:
  sass_dir: css

  # Social icons
show_social_icons: true
github_username: missymagenta
facebook_username: alina.soare.1420

# plugins
plugins: [jekyll-paginate]
paginate: 3